name: Repository Maintenance

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Kareem-3del'

    steps:
    - name: Close stale issues and PRs
      uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. Thank you for your contributions.
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. Thank you for your contributions.
        close-issue-message: |
          This issue has been automatically closed due to inactivity.
          If you believe this issue is still relevant, please reopen it.
        close-pr-message: |
          This pull request has been automatically closed due to inactivity.
          If you believe this PR is still relevant, please reopen it.
        days-before-stale: 60
        days-before-close: 7
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'enhancement,bug,documentation'
        exempt-pr-labels: 'enhancement,bug,documentation'