name: Status Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This job depends on all other critical checks
  status-check:
    runs-on: ubuntu-latest
    needs: [validate-project, quick-test]

    steps:
    - name: All checks passed
      run: echo "All status checks have passed successfully!"

  validate-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Validate project structure
      run: |
        # Check required files exist
        required_files=("package.json" "package-lock.json" "tsconfig.json" "jest.config.js")
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "Error: Required file $file is missing!"
            exit 1
          fi
        done

        # Check required directories exist
        required_dirs=("src" "test")
        for dir in "${required_dirs[@]}"; do
          if [ ! -d "$dir" ]; then
            echo "Error: Required directory $dir is missing!"
            exit 1
          fi
        done

    - name: Validate package.json
      run: |
        node -e "
          const pkg = require('./package.json');

          // Check required fields
          const required = ['name', 'version', 'description', 'main', 'types'];
          for (const field of required) {
            if (!pkg[field]) {
              console.error(\`Error: package.json missing required field: \${field}\`);
              process.exit(1);
            }
          }

          // Validate scoped package name
          if (!pkg.name.startsWith('@')) {
            console.error('Error: Package should be scoped (start with @)');
            process.exit(1);
          }

          // Validate scripts
          const requiredScripts = ['build', 'test'];
          for (const script of requiredScripts) {
            if (!pkg.scripts || !pkg.scripts[script]) {
              console.error(\`Error: package.json missing required script: \${script}\`);
              process.exit(1);
            }
          }

          console.log('package.json validation passed');
        "

  quick-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Quick build test
      run: npm run build

    - name: Quick test run
      run: npm test -- --passWithNoTests